import test from 'node:test';
import assert from 'node:assert/strict';
import {CATALOG, initial, reduce, replay} from '../web/core.mjs';
import {buildCloseout, exportCompleteCSV} from '../web/closeout.mjs';
let sequence = 0;
const turn = (s, text) => reduce(s, {kind:'turn',id:'closeout:'+sequence++,text,source:'typed',confidence:1,final:true,revision:s.revision});
const confirm = s => reduce(s,{kind:'confirm',revision:s.revision});
const countAll = () => Object.entries(CATALOG).reduce((s,[sku,item],i)=>confirm(turn(s,`${sku} ${[9,27,16,18][i]} ${item.unit}`)),initial());
test('empty stocktake is incomplete; missing items are null, never zero',()=>{const c=buildCloseout(initial());assert.equal(c.complete,false);assert.equal(c.totals.not_counted,4);assert.ok(c.rows.every(r=>r.confirmed_quantity===null));});
test('a draft is review work, not a confirmed item',()=>{const c=buildCloseout(turn(initial(),'beans 27 bags'));assert.deepEqual(c.totals,{scope:4,confirmed:0,needs_review:1,not_counted:3});assert.equal(c.complete,false);});
test('confirmed zero is different from not counted',()=>{const c=buildCloseout(confirm(turn(initial(),'soap 0 bars')));assert.equal(c.rows.find(x=>x.sku==='soap').confirmed_quantity,0);assert.equal(c.totals.confirmed,1);assert.equal(c.totals.not_counted,3);});
test('parked work stays unresolved when another item is confirmed',()=>{let s=turn(initial(),'beans 27 bags');s=turn(s,'oil');s=turn(s,'16 bottles');s=turn(s,'confirm 16');const c=buildCloseout(s);assert.equal(c.totals.needs_review,1);assert.equal(c.totals.confirmed,1);assert.equal(c.rows.find(x=>x.sku==='beans').status,'needs_review');assert.throws(()=>exportCompleteCSV(s),/Resolve/);});
test('a new draft prevents a prior confirmed count masquerading as closed',()=>{const s=turn(countAll(),'soap 19 bars');const c=buildCloseout(s);assert.equal(c.complete,false);assert.equal(c.rows.find(x=>x.sku==='soap').confirmed_quantity,18);assert.equal(c.rows.find(x=>x.sku==='soap').status,'needs_review');});
test('audio integrity hold blocks final export even with four confirmed rows',()=>{let s=countAll();s=reduce(s,{kind:'hold',reason:'stream_lost',revision:s.revision});assert.equal(buildCloseout(s).complete,false);assert.throws(()=>exportCompleteCSV(s));});
test('four explicitly confirmed items and no unresolved work allows final export',()=>{const s=countAll();assert.equal(buildCloseout(s).complete,true);assert.match(exportCompleteCSV(s),/Beans,27,bags/);assert.equal(buildCloseout(s).totals.confirmed,4);});
test('review handoff is replay-derived and stable without transcript content',()=>{const s=countAll();const c=buildCloseout(s);assert.deepEqual(buildCloseout(replay(s.history)),c);assert.doesNotMatch(JSON.stringify(c),/beans 27 bags/);assert.ok(c.rows.every(r=>r.confirmation_method==='on_screen'));});
test('typed confirmation is distinguished from on-screen confirmation',()=>{let s=turn(initial(),'oil 16 bottles');s=turn(s,'confirm 16');assert.equal(buildCloseout(s).rows.find(x=>x.sku==='oil').confirmation_method,'typed');});
test('cannot use malformed counts as completed stocktake evidence',()=>{const s=countAll();s.counts.beans.quantity=-1;assert.throws(()=>buildCloseout(s));});
test('closeout is read-only',()=>{const s=countAll(),before=structuredClone(s);buildCloseout(s);assert.deepEqual(s,before);});
test('arbitrary quantities work across all catalogue items, not one memorized example',()=>{let seed=20260922;for(let i=0;i<128;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const quantity=seed%10000;for(const [sku,item] of Object.entries(CATALOG)){const s=confirm(turn(initial(),`${sku} ${quantity} ${item.unit}`));assert.equal(buildCloseout(s).rows.find(x=>x.sku===sku).confirmed_quantity,quantity);}}});
