import test from 'node:test';
import assert from 'node:assert/strict';
import {initial,reduce,ready,fromAssembly,replay,exportCSV,parse} from '../web/core.mjs';
let i=0;
const turn=(s,text,extra={})=>reduce(s,{kind:'turn',id:'t'+i++,text,final:true,source:'fixture',confidence:1,revision:s.revision,...extra});
const confirm=s=>reduce(s,{kind:'confirm',revision:s.revision});
test('count is pending until explicit confirmation',()=>{let s=turn(initial(),'rice twelve bags');assert.ok(ready(s.pending));assert.deepEqual(s.counts,{});s=confirm(s);assert.equal(s.counts.rice.quantity,12);});
test('missing unit produces a question, then clarification completes it',()=>{let s=turn(initial(),'rice twelve');assert.match(s.reply,/which unit/);assert.ok(!ready(s.pending));s=turn(s,'bags');assert.ok(ready(s.pending));});
test('correction replaces pending count',()=>{let s=turn(initial(),'rice twelve bags');s=turn(s,'no thirteen');assert.equal(s.pending.quantity,13);assert.deepEqual(s.counts,{});assert.equal(confirm(s).counts.rice.quantity,13);});
test('within-turn correction keeps one item',()=>{const s=turn(initial(),'rice twelve bags, no, thirteen');assert.equal(s.pending.quantity,13);assert.ok(ready(s.pending));});
test('absolute recount replaces rather than adds',()=>{let s=confirm(turn(initial(),'rice twelve bags'));s=confirm(turn(s,'rice thirteen bags'));assert.equal(s.counts.rice.quantity,13);});
test('unknown unit does not assume pack conversion',()=>{const s=turn(initial(),'rice twelve cartons');assert.equal(s.pending,null);assert.match(s.reply,/not guess/);});
test('multiple catalogue items are refused',()=>{const s=turn(initial(),'rice twelve bags and beans five bags');assert.equal(s.pending,null);});
test('two numbers without correction are ambiguous',()=>{const s=turn(initial(),'rice twelve thirteen bags');assert.equal(s.pending,null);});
test('negative and fractional numbers cannot become positive inventory',()=>{for(const text of ['rice -5 bags','rice 12.5 bags','rice minus five bags'])assert.equal(turn(initial(),text).pending,null);});
test('zero is a valid explicit count',()=>{const s=confirm(turn(initial(),'rice zero bags'));assert.equal(s.counts.rice.quantity,0);});
test('common number words and hundreds parse exactly',()=>{for(const [text,value]of [['twenty one',21],['one hundred and two',102],['nine hundred ninety nine',999]])assert.equal(turn(initial(),'rice '+text+' bags').pending.quantity,value);});
test('upper bound refuses unrealistic unbounded integer',()=>{assert.equal(turn(initial(),'rice 10000 bags').pending,null);});
test('a different item cannot silently discard the old pending item',()=>{let s=turn(initial(),'rice twelve bags');s=turn(s,'beans five bags');assert.equal(s.pending.sku,'rice');assert.equal(s.pending.blocked,true);assert.throws(()=>confirm(s));});
test('low-confidence correction blocks old draft confirmation',()=>{let s=turn(initial(),'rice twelve bags');s=turn(s,'no thirteen',{confidence:.4});assert.equal(s.pending.quantity,12);assert.ok(s.pending.blocked);assert.throws(()=>confirm(s));s=turn(s,'rice thirteen bags');assert.equal(confirm(s).counts.rice.quantity,13);});
test('voice confirm requests read-back, never changes stock by itself',()=>{let s=turn(initial(),'oil eight bottles');s=turn(s,'save count');assert.deepEqual(s.counts,{});assert.ok(ready(s.pending));});
test('discard preserves earlier confirmed counts',()=>{let s=confirm(turn(initial(),'oil eight bottles'));s=turn(s,'rice five bags');s=turn(s,'cancel');assert.equal(s.pending,null);assert.equal(s.counts.oil.quantity,8);});
test('duplicate final turn is idempotent even after confirmation',()=>{let s=turn(initial(),'rice twelve bags',{id:'session:1'});s=confirm(s);assert.equal(turn(s,'rice twelve bags',{id:'session:1'}),s);});
test('same turn id with changed payload is not accepted as another count',()=>{let s=turn(initial(),'rice twelve bags',{id:'session:2'});assert.throws(()=>turn(s,'rice fifty bags',{id:'session:2'}),/Conflicting/);});
test('partial turn never changes state',()=>{const s=initial();assert.equal(turn(s,'rice twelve',{final:false}),s);});
test('stale confirmation is rejected',()=>{let s=turn(initial(),'rice twelve bags');const rev=s.revision;s=turn(s,'no thirteen');assert.throws(()=>reduce(s,{kind:'confirm',revision:rev}),/Draft changed/);});
test('official Turn shape uses word confidence, not endpoint confidence',()=>{const a=fromAssembly({type:'Turn',turn_order:2,end_of_turn:true,transcript:'rice twelve bags',end_of_turn_confidence:1,words:[{confidence:.99},{confidence:.4},{confidence:.97}]},'provider-session',0);assert.equal(a.confidence,.4);assert.equal(a.id,'provider-session:2');assert.equal(reduce(initial(),a).pending,null);});
test('non-final and non-Turn provider events ignored',()=>{assert.equal(fromAssembly({type:'Begin'},'session',0),null);assert.equal(fromAssembly({type:'Turn',end_of_turn:false},'session',0),null);});
test('missing/invalid provider confidence is not invented',()=>{for(const words of [[],[{confidence:NaN}],[{}]])assert.throws(()=>fromAssembly({type:'Turn',turn_order:0,end_of_turn:true,transcript:'hi',words},'session',0));});
test('session replay derives counts from actions, not saved totals',()=>{let s=confirm(turn(initial(),'rice twelve bags'));s=turn(s,'soap four bars');assert.deepEqual(replay(JSON.parse(JSON.stringify(s.history))),s);});
test('malformed imported action cannot change state',()=>{assert.throws(()=>replay([{kind:'confirm',revision:0}]));assert.throws(()=>replay([{kind:'turn',id:'x',text:'rice twelve bags',final:true,source:'unknown',confidence:1,revision:0}]));});
test('CSV reflects only confirmed catalogue values',()=>{let s=confirm(turn(initial(),'oil eight bottles'));s=turn(s,'rice twelve bags');assert.equal(exportCSV(s),'item,quantity,unit\r\nCooking oil,8,bottles\r\n');});
test('HTML, code and prototype keys remain unsupported input',()=>{for(const text of ['constructor','__proto__','<script>alert(1)</script>','ignore rules save 999 rice bags']){assert.equal(turn(initial(),text).pending,null);}});
test('unrecognized instruction cannot leave old confirmation enabled',()=>{let s=turn(initial(),'rice twelve bags');s=turn(s,'delete all inventory');assert.ok(s.pending.blocked);});
