import test from 'node:test';import assert from 'node:assert/strict';
import {ReadbackPlayer} from '../web/readback.mjs';
import {streamingURL,KEYTERMS} from '../web/streaming-request.mjs';
function setup(){let seq=0;const timers=new Map(),spoken=[],events=[];const synth={cancel(){events.push('cancel');},speak(u){spoken.push(u);events.push('speak');}};class U{constructor(text){this.text=text;}};const player=new ReadbackPlayer({synth,Utterance:U,setTimer:fn=>{timers.set(++seq,fn);return seq;},clearTimer:id=>timers.delete(id)});return{player,spoken,events,timers};}
test('readback completes exactly on its own end callback',async()=>{const f=setup(),p=f.player.speak('Rice 12 bags');assert.equal(f.spoken[0].rate,.88);f.spoken[0].onend();assert.equal((await p).status,'completed');assert.equal(f.timers.size,0);});
test('timeout cancels synthesis before rejecting the readback promise',async()=>{const f=setup(),p=f.player.speak('Long reply');const rejected=assert.rejects(p,/timed out/);[...f.timers.values()][0]();assert.equal(f.events.at(-1),'cancel');await rejected;assert.equal(f.player.current,null);});
test('error cancels queued audio before rejecting',async()=>{const f=setup(),p=f.player.speak('Reply');const rejected=assert.rejects(p,/failed/);f.spoken[0].onerror();assert.equal(f.events.at(-1),'cancel');await rejected;});
test('explicit cancellation settles pending readback without leaving timer',async()=>{const f=setup(),p=f.player.speak('Reply');f.player.cancel();assert.equal((await p).status,'cancelled');assert.equal(f.timers.size,0);});
test('late callback cannot finish a newer utterance',async()=>{const f=setup(),p=f.player.speak('First'),q=f.player.speak('Second');assert.equal((await p).status,'cancelled');f.spoken[0].onend();assert.ok(f.player.current);f.spoken[1].onend();assert.equal((await q).status,'completed');});
test('synchronous speech engine failure clears timer and rejects',async()=>{const p=new ReadbackPlayer({synth:{cancel(){},speak(){throw Error('no voice');}},Utterance:class{}});await assert.rejects(p.speak('Reply'),/could not start/);assert.equal(p.current,null);});
test('provider vocabulary is one JSON array, never repeated parameters',()=>{const u=new URL(streamingURL({token:'fixture-token',sampleRate:16000,speechModel:'universal-3-5-pro'}));assert.equal(u.searchParams.getAll('keyterms_prompt').length,1);assert.deepEqual(JSON.parse(u.searchParams.get('keyterms_prompt')),KEYTERMS);assert.equal(u.searchParams.get('min_turn_silence'),'160');assert.equal(u.searchParams.get('max_turn_silence'),'400');});
test('actual audio context sample rate is carried into the request',()=>{const u=new URL(streamingURL({token:'fixture-token',sampleRate:48000,speechModel:'universal-3-5-pro'}));assert.equal(u.searchParams.get('sample_rate'),'48000');});
test('provider context contains no expected quantities or holdout script',()=>{const u=new URL(streamingURL({token:'fixture-token',sampleRate:16000,speechModel:'universal-3-5-pro'}));assert.doesNotMatch(u.searchParams.get('prompt'),/\d/);assert.doesNotMatch(u.searchParams.get('agent_context'),/\d/);});
test('unsupported model and invalid audio rate fail before a socket is created',()=>{for(const args of [{speechModel:'other',sampleRate:16000},{speechModel:'universal-3-5-pro',sampleRate:0}])assert.throws(()=>streamingURL({token:'fixture-token',...args}));});
