// Offline documented-request checks only; never calls a provider.
import test from 'node:test';
import assert from 'node:assert/strict';
import {buildStreamingURL,makeRedactor,safeEvent} from '../diagnostics/request-contract.mjs';
const token='test-temporary-token-1234';
const base={speech_model:'universal-3-5-pro',min_turn_silence:160,max_turn_silence:640,prompt:'An inventory stocktake.',agent_context:'Name an item, count, and unit.',keyterms_prompt:['cooking oil','soap']};
test('keyterms occupy exactly one JSON-array query value',()=>{const q=new URL(buildStreamingURL(token,base)).searchParams;assert.equal(q.getAll('keyterms_prompt').length,1);assert.deepEqual(JSON.parse(q.get('keyterms_prompt')),base.keyterms_prompt);});
test('old repeated-key encoding fails the documented JSON-array contract',()=>{const q=new URLSearchParams();for(const term of base.keyterms_prompt)q.append('keyterms_prompt',term);assert.equal(q.getAll('keyterms_prompt').length,2);assert.throws(()=>JSON.parse(q.get('keyterms_prompt')));});
test('current bounded low-latency timings are preserved without inventing a mode',()=>{const q=new URL(buildStreamingURL(token,base)).searchParams;assert.equal(q.get('min_turn_silence'),'160');assert.equal(q.get('max_turn_silence'),'640');assert.equal(q.get('mode'),null);});
test('empty keyterms are omitted rather than an invalid parameter',()=>{assert.equal(new URL(buildStreamingURL(token,{...base,keyterms_prompt:[]})).searchParams.has('keyterms_prompt'),false);});
test('spaces, ampersands, and Unicode survive query encoding',()=>{const c={...base,keyterms_prompt:['A&B','Crème'],prompt:'food & stock'};const q=new URL(buildStreamingURL(token,c)).searchParams;assert.deepEqual(JSON.parse(q.get('keyterms_prompt')),c.keyterms_prompt);assert.equal(q.get('prompt'),c.prompt);});
test('rejects keyterms not provided as an array',()=>assert.throws(()=>buildStreamingURL(token,{...base,keyterms_prompt:'soap'})));
test('rejects too many and overlong terms',()=>{for(const terms of [Array(101).fill('soap'),['a'.repeat(51)],['']])assert.throws(()=>buildStreamingURL(token,{...base,keyterms_prompt:terms}));});
test('rejects inverted and invalid silence bounds',()=>{for(const c of [{min_turn_silence:0},{min_turn_silence:501},{max_turn_silence:400},{max_turn_silence:5001},{min_turn_silence:1.5},{max_turn_silence:Infinity}])assert.throws(()=>buildStreamingURL(token,{...base,...c}));});
test('rejects unknown model and invalid token before constructing a socket',()=>{assert.throws(()=>buildStreamingURL('x',base));assert.throws(()=>buildStreamingURL(token,{...base,speech_model:'invented'}));});
test('rejects oversized context before provider use',()=>assert.throws(()=>buildStreamingURL(token,{...base,prompt:'a'.repeat(1751)})));
test('provider Error retains numeric code and exact nonsecret explanation',()=>{assert.deepEqual(safeEvent({type:'Error',error_code:3006,error:'Invalid keyterms JSON'}),{type:'Error',error_code:3006,error:'Invalid keyterms JSON'});});
test('known secrets and URL query strings are redacted from diagnostics',()=>{const redact=makeRedactor([token,'private-judge-code']);const s=redact(`Rejected ${token} private-judge-code https://host/path?token=${token}`);assert.ok(!s.includes(token));assert.ok(!s.includes('private-judge-code'));assert.ok(!s.includes('https://host/path?'));});
test('provider configuration cannot smuggle token fields into the result',()=>{const e=safeEvent({type:'Begin',id:'s',configuration:{model:'universal-3-5-pro',token,api_key:'hidden'}});assert.deepEqual(e.configuration,{model:'universal-3-5-pro'});});
test('final transcript and word confidence are not repaired or replaced',()=>{const raw={type:'Turn',turn_order:1,end_of_turn:true,transcript:'Soup 18 bars.',words:[{text:'Soup',confidence:.7,start:1,end:2}]};assert.deepEqual(safeEvent(raw),raw);});
test('malformed messages fail rather than creating invented events',()=>{for(const v of [null,[],{},'hello'])assert.throws(()=>safeEvent(v));});
